<?php
include('fpdf/fpdf.php');  
include('session.php'); 
class PDF extends FPDF
{

// Page footer
function Footer()
{
	$Today = date('y:m:d');
 $new = date('l, F d, Y', strtotime($Today));
    // Position at 1.5 cm from bottom
    $this->SetY(-35);
    // Arial italic 8
    $this->SetFont('Arial','',12);
    // Page number
	 $this->SetX(15);
	 
	$this->Cell(70,15,'Registrar\'s Signature____________________________  ',0,1,'L');
	
		$this->SetFont('Arial','',9);
	

    $this->Cell(0,25,'Date published:'.$new.'  |  Results generated by BIU SIMS'.'  |By Tecgenius,Cell: +265992127918'.' | '.' CC: Personal file',0,0,'C');
}
}

 
                            
							
                            
include('admin/connect.php');
include('admin/functions.php');
$cyear=date('Y');
				  $csem=checksem();
				  if(($csem)==1){ $sem =2; $year = $cyear-1;}else{$sem =1; $year = $cyear;}
$query = mysqli_query($conn,"select * from results where year='$year'  and sem='$sem' and uid ='$session_id'")or die(mysqli_error($conn));
 $total=mysqli_num_rows($query);
		 if($total>0){ //open total>0 
	
		 
		if($sem==1)$TAG= "Jan-June"; else $TAG="July-Dec" ;
		                
         $df= new PDF('L','mm','A4');
		  $row = mysqli_fetch_array($query);//open loop first
		  	$styear=$row['stud_year'];
              $semm=  $row['studsem'];         
					 $uid = $row['uid'];
					 $prog=$row['prog'];
						  
						  $student2 = mysqli_query($conn,"select * from student_fees where id='$session_id' and year='$year' and sem='$sem' and fee_balance=0") or die("here".mysqli_error($conn)); 
		  $NUM=mysqli_fetch_assoc($student2);
		 $student4 = mysqli_query($conn,"select * from results where uid='$session_id' and year='$year' and sem='$sem' and comment='F' ") or die("here".mysqli_error($conn)); 
                         if(mysqli_num_rows($student4)==0)
                          {$well="Pass and Proceed"; $v=1;}
					  elseif(mysqli_num_rows($student4)>=3){$well="Repeat Semester";$v=2;}else {$well="Proceed CARRY:"; $v=3;}


$df->AddPage('P');
$df->SetTitle("Exam results",false);

$df->Image('logo.png',65,5,60);
$df->setY(15);
$df->SetFont('Times','B','18');

$df->SetFont('Times','','10');
$df->setX(100);
$df->Cell(100,5,'Private    Bag    98 Blantyre',0,1,'R');
$df->setX(100);
$df->Cell(100,5,'Telephone:+265 999279608',0,1,'R');
$df->setX(100);
$df->Cell(100,5,'Email:info@biu-edu.com',0,1,'R');
 $df->setX(100);
$df->Cell(100,5,'Website:www.biu-edu.com',0,1,'R');
$df->SetFont('Times','B','20');
$df->setY(60);

$df->Cell(190,5,'Examinations  Result Slip' ,0,1,'C');
$df->SetFont('Times','','10');
$df->Cell(190,10,'('.$TAG. '  , '.$year.')' ,0,1,'C');
$df->setFillColor(255,255,255);
$df->setY(85);
$df->setX(15);
$df->SetFont('Times','','11');
$df->setX(15);
$df->Cell(100,9,'Student Names:         '.$row['surname'].' , '.$row['firstname'],0,1,'L');
$df->setX(15);
$df->Cell(50,9,'Student ID:                '.$row['student_id'],0,1,'L');
$df->setX(15);
$df->Cell(50,9,'Programe:                  '.$prog,0,1,'L');
$df->setX(15);

$df->Cell(80,9,'Current year:             '.$styear,0,1,'L');
$df->setX(15);
$df->Cell(50,9,'Current Semester:     '.$semm,0,1,'L');
$df->setX(15);
$df->Cell(70,9,'Exam No:                  '.$NUM['exam_no'],0,1,'L');
$in=140;
$y=6;
$df->SetFont('Times','B','14');
  if(mysqli_num_rows($student2)==0){
	  $df->setX(25);
							   $df->Cell(200,60,'Please consult the accounts office',0,0,'C');
							    $df->setX(15);
							  }
							  else
							  { 

$df->SetFont('Times','','12');
$df->setTextColor(22.7,52.9,67.8);
$df->setTextColor(58,135,173);
$df->setY($in);
$df->setX(15);
$df->setFillColor(217,237,247);
$df->setDrawColor(188,232,214);
$df->Cell(10,7,'NO',0,0,'L',1);
$df->Cell(20,7,'Code',0,0,'C',1);
$df->Cell(79,7,'Course Name',0,0,'L',1);

$df->Cell(10,7,'CW1',0,0,'C',1);
$df->Cell(10,7,'CW2',0,0,'C',1);
$df->Cell(15,7,'Exam',0,0,'C',1);
$df->Cell(15,7,'EOS',0,0,'C',1);
$df->Cell(17,7,'Grade',0,1,'C',1);
$y=$y+$in;
$i=1;
$z=1;	
$yin=20;
				
$df->setTextColor(0,0,0);
$MYQ = mysqli_query($conn,"select * from results where uid='$session_id' and year='$year' and sem='$sem'") or die(mysqli_error($conn)); 

while($student_row = mysqli_fetch_array($MYQ)){//open subject loop
							$cod=$student_row ['course_code'];
                          $title= mysqli_query($conn,"select * from subject where subject_code='$cod' ")or die(mysqli_error($conn));
						  $ccode=mysqli_fetch_array($title);
	if($student_row['assign_1']==0 or $student_row['assign_2']==0 or $student_row['EOS']==0) $com= "N/A"; else $com= $student_row['comment'];
	 

	
	

		
	
	
	if($i%2==0)
		$df->setFillColor(232,232,232);
	
else
	
$df->setFillColor(255,255,255);
	if($z<7){
$df->SetX(15);
$df->Cell(10,7,$i,0,0,'L',1);
$df->Cell(20,7,$student_row['course_code'],0,0,'C',1);
$df->Cell(79,7,$ccode['subject_title'],0,0,'L',1);

$df->Cell(10,7,$student_row['assign_1'],0,0,'C',1);
$df->Cell(10,7,$student_row['assign_2'],0,0,'C',1);
$df->Cell(15,7,$student_row['EOS'],0,0,'C',1);
$df->Cell(15,7,$student_row['fgrade'],0,0,'C',1);
$df->Cell(17,7,$com,0,1,'C',1);
$i++;
$y=$yin;
$y=$y+$in;
$z++;
}	
}//cose loop
 $df->SetX(15);
									
									 $df->SetX(15);
									//$df->Cell(70,6,'Published:'.$new,0,1,'L');
									$df->SetFont('Times','','11');
 $df->SetX(15);
 $df->Cell(70,8,'',0,1,'L');	
 $df->SetFont('Times','','9');
$df->Cell(70,5,'Note: All failed courses MUST be done the next semester and the MAXIMUM number of courses per semester(including carryovers) is six(6). ',0,1,'L');
 $df->SetX(15);
$df->Cell(70,5,'All courses you will take(in place of carryovers) will be null and void and a waste of time so do the carryovers first. ',0,1,'L');	
 $df->SetX(15);	
 $df->Cell(70,5,'This is because all carryovers are automatically registered, so whether you register them or not they will be on your course list. ',0,1,'L');	
$df->SetFont('Times','B','12');
 $df->Cell(70,8,'Remarks:'.$well,0,1,'L');
 $df->SetFont('Times','','12');
									if($v==3)
									{
								
									$x=1;
									while($rs=mysqli_fetch_array($student4))
									{
											$df->SetX(15);
									$cc=$rs['course_code'];	
									$title= mysqli_query($conn,"select * from subject where subject_code='$cc' ");
                                     $su=mysqli_fetch_array($title)	;
									 $sname= $su['subject_title'];
                                    $df->Cell(10,6, $x.'.'.$sname,0,1,'L');
									$x++;
								   
                                 								 
									}
                                    								
									}
									
									
									
									
									
		}//close no fees
		  //}//close first loop
		   
		 }//close total
		

$df->Output();
?>